package Programa;

import Conversores.Area;
import Conversores.Armazenamento;
import Conversores.Comprimento;
import Conversores.Frequencia;
import Conversores.Liquido;
import Conversores.Massa;
import Conversores.Pressao;
import Conversores.Temperatura;
import Conversores.Tempo;
import Conversores.Velocidade;
import javax.swing.JComboBox;

public class programa extends javax.swing.JFrame {

    private double valor;
    private String categoria;
    private String converter_de;
    private String converter_para;
    private String valorConvertido;

        
    Area area = new Area();
    Armazenamento armazenamento = new Armazenamento();
    Comprimento comprimento = new Comprimento();
    Frequencia frequencia = new Frequencia();
    Liquido liquido = new Liquido();
    Massa massa = new Massa();
    Pressao pressao = new Pressao();
    Temperatura temperatura = new Temperatura();
    Tempo tempo = new Tempo();
    Velocidade velocidade = new Velocidade();
    
    
    /**
     * Creates new form programa
     */
    public programa() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_de = new javax.swing.JLabel();
        label_para = new javax.swing.JLabel();
        valor_de = new javax.swing.JTextField();
        valor_para = new javax.swing.JTextField();
        seletor_de = new javax.swing.JComboBox<>();
        seletor_para = new javax.swing.JComboBox<>();
        seletor_categoria = new javax.swing.JComboBox<>();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuItemAjuda = new javax.swing.JMenuItem();
        menuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Medidas");
        setAlwaysOnTop(true);
        setResizable(false);

        label_de.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_de.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_de.setText("Converter de");
        label_de.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_para.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_para.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_para.setText("Converter para");
        label_para.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valor_de.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valor_de.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_de.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        valor_de.setName(""); // NOI18N
        valor_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_deActionPerformed(evt);
            }
        });

        valor_para.setEditable(false);
        valor_para.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valor_para.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor_para.setName("valor_para"); // NOI18N
        valor_para.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_paraActionPerformed(evt);
            }
        });

        seletor_de.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seletor_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletor_deActionPerformed(evt);
            }
        });

        seletor_para.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seletor_para.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletor_paraActionPerformed(evt);
            }
        });

        seletor_categoria.setMaximumRowCount(10);
        seletor_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Área", "Armazenamento de Dados", "Comprimento", "Frequência", "Líquido", "Massa", "Pressão", "Temperatura", "Tempo", "Velocidade" }));
        seletor_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletor_categoriaActionPerformed(evt);
            }
        });

        menuFile.setText("File");

        menuItemSair.setText("Sair");
        menuFile.add(menuItemSair);

        menuBar.add(menuFile);

        menuAjuda.setText("Ajuda");

        menuItemAjuda.setText("Ajuda");
        menuAjuda.add(menuItemAjuda);

        menuItemSobre.setText("Sobre");
        menuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuItemSobre);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_de, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_para, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valor_de, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_para, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seletor_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletor_para, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletor_de, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(seletor_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_de, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_de, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletor_de, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_para, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_para, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seletor_para, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        seletor_para.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valor_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_deActionPerformed
        
        
        valor = Double.parseDouble(valor_de.getText());
    }//GEN-LAST:event_valor_deActionPerformed
    private void seletor_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletor_deActionPerformed
        String[] lista = {};
        JComboBox seletor_de = new JComboBox(lista);
        
        converter_de = (String)seletor_de.getSelectedItem();
    }//GEN-LAST:event_seletor_deActionPerformed
    private void seletor_paraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletor_paraActionPerformed
        converter_para = (String)seletor_para.getSelectedItem();
    }//GEN-LAST:event_seletor_paraActionPerformed
    private void valor_paraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_paraActionPerformed
                valor_para.setText(valorConvertido);
    }//GEN-LAST:event_valor_paraActionPerformed
    private void seletor_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletor_categoriaActionPerformed
        categoria = (String)seletor_categoria.getSelectedItem();
    }//GEN-LAST:event_seletor_categoriaActionPerformed

    private void menuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_de;
    private javax.swing.JLabel label_para;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemAjuda;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSobre;
    private javax.swing.JComboBox<String> seletor_categoria;
    private javax.swing.JComboBox<String> seletor_de;
    private javax.swing.JComboBox<String> seletor_para;
    private javax.swing.JTextField valor_de;
    private javax.swing.JTextField valor_para;
    // End of variables declaration//GEN-END:variables
}
